# Generated by Django 5.2.9 on 2025-12-08 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
        ("questions", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="normalized_text",
            field=models.TextField(
                blank=True, help_text="Normalized text for clustering/matching"
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="topic_cluster",
            field=models.ForeignKey(
                blank=True,
                help_text="Topic cluster this question belongs to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="questions",
                to="analytics.topiccluster",
            ),
        ),
    ]
