# Generated by Django 5.2.9 on 2025-12-10 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0003_question_part_question_topic_cluster"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="frequency_score",
            field=models.FloatField(
                default=0.0, help_text="Frequency score across years"
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="images",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of extracted images with bbox coordinates and base64 data",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="importance_score",
            field=models.FloatField(
                default=0.0,
                help_text="Calculated importance score based on frequency and recency",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("definition", "Definition"),
                    ("derivation", "Derivation"),
                    ("numerical", "Numerical Problem"),
                    ("theory", "Theoretical"),
                    ("diagram", "Diagram-based"),
                    ("comparison", "Comparison"),
                    ("short_answer", "Short Answer"),
                    ("long_answer", "Long Answer"),
                ],
                help_text="Type of question classified by LLM",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="repetition_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of times this question appeared across papers",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="years_appeared",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of years when this question appeared",
            ),
        ),
    ]
