# Generated by Django 5.2.9 on 2025-12-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subjects", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="exam_pattern",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Question-to-module mapping pattern (e.g., KTU standard)",
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="tier_thresholds",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Thresholds for priority tiers (e.g., {"tier_1": 4, "tier_2": 3, "tier_3": 2})',
            ),
        ),
    ]
