# Generated by Django 5.2.9 on 2025-12-10 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subjects", "0003_exampattern"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="subject",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="subject",
            name="syllabus_text",
            field=models.TextField(
                blank=True, help_text="Extracted syllabus text for semantic matching"
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="university_type",
            field=models.CharField(
                choices=[
                    ("KTU", "KTU (APJ Abdul Kalam Technological University)"),
                    ("OTHER", "Other University"),
                ],
                default="KTU",
                help_text="KTU uses rule-based mapping, Other uses AI classification",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="syllabus_file",
            field=models.FileField(
                blank=True,
                help_text="Optional: Upload syllabus for better AI classification",
                null=True,
                upload_to="syllabi/",
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subjects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
