# Generated by Django 5.2.9 on 2025-12-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("papers", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paper",
            name="university",
            field=models.CharField(
                choices=[
                    ("ktu", "KTU (APJ Abdul Kalam Technological University)"),
                    ("other", "Other University"),
                ],
                default="ktu",
                help_text="University for classification rules",
                max_length=50,
            ),
        ),
    ]
