# Generated by Django 5.2.9 on 2025-12-08 17:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("subjects", "0003_subject_exam_pattern_subject_tier_thresholds"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubjectAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("total_questions", models.PositiveIntegerField(default=0)),
                ("unique_topics", models.PositiveIntegerField(default=0)),
                ("papers_analyzed", models.PositiveIntegerField(default=0)),
                (
                    "tier_1_topics",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of top priority topics"
                    ),
                ),
                (
                    "tier_2_topics",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of high priority topics"
                    ),
                ),
                (
                    "tier_3_topics",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of medium priority topics"
                    ),
                ),
                (
                    "tier_4_topics",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of low priority topics"
                    ),
                ),
                (
                    "top_topics_by_module",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Top 3 topics per module with their stats",
                    ),
                ),
                (
                    "module_question_counts",
                    models.JSONField(
                        blank=True, default=dict, help_text="Question counts per module"
                    ),
                ),
                (
                    "years_covered",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of years with analyzed papers",
                    ),
                ),
                (
                    "last_analyzed",
                    models.DateTimeField(
                        auto_now=True, help_text="Last time analytics were computed"
                    ),
                ),
                (
                    "subject",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="subjects.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subject Analytics",
                "verbose_name_plural": "Subject Analytics",
            },
        ),
        migrations.CreateModel(
            name="TopicCluster",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "topic_name",
                    models.CharField(
                        help_text="Human-readable topic name", max_length=500
                    ),
                ),
                (
                    "normalized_key",
                    models.CharField(
                        db_index=True,
                        help_text="Normalized text for matching",
                        max_length=500,
                    ),
                ),
                (
                    "frequency_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times this topic appears across all papers",
                    ),
                ),
                (
                    "years_appeared",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of years when this topic appeared",
                    ),
                ),
                (
                    "papers_appeared",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of paper IDs where this topic appeared",
                    ),
                ),
                (
                    "priority_tier",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (4, "Low Priority (1 exam)"),
                            (3, "Medium Priority (2 exams)"),
                            (2, "High Priority (3 exams)"),
                            (1, "Top Priority (4+ exams)"),
                        ],
                        help_text="Priority tier based on frequency",
                        null=True,
                    ),
                ),
                (
                    "total_marks",
                    models.PositiveIntegerField(
                        default=0, help_text="Total marks across all occurrences"
                    ),
                ),
                (
                    "avg_marks",
                    models.FloatField(
                        default=0.0, help_text="Average marks per question"
                    ),
                ),
                (
                    "representative_question",
                    models.TextField(
                        blank=True,
                        help_text="Representative question text for this topic",
                    ),
                ),
                (
                    "embedding_centroid",
                    models.JSONField(
                        blank=True,
                        help_text="Average embedding vector for this cluster",
                        null=True,
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topic_clusters",
                        to="subjects.module",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topic_clusters",
                        to="subjects.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Topic Cluster",
                "verbose_name_plural": "Topic Clusters",
                "ordering": ["module__number", "-frequency_count", "topic_name"],
                "unique_together": {("subject", "module", "normalized_key")},
            },
        ),
    ]
